[tool.black]
line-length = 120

[tool.mypy]
python_version = "3.13"
warn_return_any = true
ignore_missing_imports = true
# disallow_untyped_defs = true TODO: włączyć później

[tool.pytest.ini_options]
pythonpath = ["src"]
testpaths = ["tests"]
